{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nodeport-loadbalancer.fullname" . }}
  labels:
    {{- include "nodeport-loadbalancer.labels" . | nindent 4 }}
rules:
- apiGroups: ['']
  resources: [nodes]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [services]
  verbs: [get, list, watch]
- apiGroups: ['']
  resources: [services/status]
  verbs: [get, list, watch, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "nodeport-loadbalancer.fullname" . }}-leader-election
  labels:
    {{- include "nodeport-loadbalancer.labels" . | nindent 4 }}
rules:
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [get, list, watch, create, update, patch]
- apiGroups: ['']
  resources: [events]
  verbs: [create]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nodeport-loadbalancer.fullname" . }}
  labels:
    {{- include "nodeport-loadbalancer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nodeport-loadbalancer.fullname" . }}
subjects:
- apiGroup: ''
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "nodeport-loadbalancer.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "nodeport-loadbalancer.fullname" . }}
  labels:
    {{- include "nodeport-loadbalancer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "nodeport-loadbalancer.fullname" . }}-leader-election
subjects:
- apiGroup: ''
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "nodeport-loadbalancer.fullname" . }}
{{- end }}

