apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodeport-loadbalancer.fullname" . }}
  labels:
    {{- include "nodeport-loadbalancer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "nodeport-loadbalancer.selectorLabels" . | nindent 4 }}
